# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 10:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaEntrada', models.TimeField()),
                ('horaSortida', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaInici', models.TimeField()),
                ('horaFinal', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Dispositiu',
            fields=[
                ('MAC', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('codi', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('nom', models.CharField(max_length=256)),
                ('MAC', models.CharField(max_length=17, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Alumne',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='API.UserProfile')),
                ('dni', models.CharField(max_length=8, unique=True)),
            ],
            bases=('API.userprofile',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='API.UserProfile')),
                ('something', models.CharField(max_length=256)),
            ],
            bases=('API.userprofile',),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classe',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Sala'),
        ),
        migrations.AddField(
            model_name='assistencia',
            name='classeAlumne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Classe'),
        ),
        migrations.AddField(
            model_name='assistencia',
            name='dispositiuAlumne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Dispositiu'),
        ),
        migrations.AddField(
            model_name='classe',
            name='professorTutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Professor'),
        ),
        migrations.AddField(
            model_name='alumne',
            name='classes',
            field=models.ManyToManyField(to='API.Classe'),
        ),
        migrations.AddField(
            model_name='alumne',
            name='dispositiu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.Dispositiu'),
        ),
    ]
