# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 18:18
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('inici', models.DateField()),
                ('final', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Assistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField()),
                ('sortida', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(blank=True, choices=[(b'dilluns', 'Dilluns'), (b'dimarts', 'Dimarts'), (b'dimecres', 'Dimecres'), (b'dijous', 'Dijous'), (b'divendres', 'Divendres')], max_length=10)),
                ('horaInici', models.TimeField()),
                ('horaFinal', models.TimeField()),
                ('assignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Assignatura')),
            ],
        ),
        migrations.CreateModel(
            name='ClasseAlumne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Classe')),
            ],
        ),
        migrations.CreateModel(
            name='ClasseProfe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Classe')),
            ],
        ),
        migrations.CreateModel(
            name='Dispositiu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MAC', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(code=b'invalid_mac', message=b'MAC no valida', regex=b'^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')])),
                ('codi', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('MAC', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(code=b'invalid_mac', message=b'MAC no valida', regex=b'^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')])),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='API.UserProfile')),
                ('uni', models.CharField(max_length=20)),
            ],
            bases=('API.userprofile',),
        ),
        migrations.CreateModel(
            name='Alumne',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='API.UserProfile')),
                ('dni', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message=b'El DNI/NIE no es valid', regex=b' (([X-Z]{1})([-]?)(\\d{7})([-]?)([A-Z]{1}))|((\\d{8})([-]?)([A-Z]{1}))')])),
                ('dispositiu', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Dispositiu')),
            ],
            bases=('API.userprofile',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='API.UserProfile')),
                ('uni', models.CharField(max_length=20)),
            ],
            bases=('API.userprofile',),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classe',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Sala'),
        ),
        migrations.AddField(
            model_name='assistencia',
            name='classeAlumne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.ClasseAlumne'),
        ),
        migrations.AddField(
            model_name='classeprofe',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Professor'),
        ),
        migrations.AddField(
            model_name='classealumne',
            name='alumne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Alumne'),
        ),
    ]
