# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='something',
        ),
        migrations.AddField(
            model_name='professor',
            name='classes',
            field=models.ManyToManyField(to='API.Classe'),
        ),
    ]
