# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20170413_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseAlumne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='alumne',
            name='classes',
        ),
        migrations.AddField(
            model_name='classealumne',
            name='alumne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Alumne'),
        ),
        migrations.AddField(
            model_name='classealumne',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Classe'),
        ),
    ]
