# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20170516_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='horaFinal',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='classe',
            name='horaInici',
            field=models.TimeField(),
        ),
    ]
