# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20170413_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositiu',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sala',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispositiu',
            name='MAC',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='MAC',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
