# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20170415_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumne',
            name='dispositiu',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Dispositiu'),
        ),
    ]
