# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20170516_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignatura',
            name='codiassig',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
