# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20170415_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='dia',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
