# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_classe_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='dia',
            field=models.CharField(max_length=20),
        ),
    ]
