# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20170416_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='dia',
            field=models.IntegerField(),
        ),
    ]
