# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 09:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_auto_20170430_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='dia',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
