# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_auto_20170501_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classe',
            old_name='dia',
            new_name='dies',
        ),
    ]
