# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_auto_20170508_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classe',
            old_name='dies',
            new_name='dia',
        ),
    ]
